basePath: /api/v1
definitions:
  httpErrors.RestErr:
    type: object
  httpErrors.RestError:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  models.Comment:
    properties:
      author_id:
        type: string
      comment_id:
        type: string
      created_at:
        type: string
      likes:
        type: integer
      message:
        type: string
      news_id:
        type: string
      updated_at:
        type: string
    required:
      - author_id
      - message
      - news_id
    type: object
info:
  contact:
    email: ilhanemir1@gmail.com
    name: İlhan Emir
    url: https://github.com/hanzales
  description: MyMechanic REST API
  title: MyMechanic REST API
  version: "1.0"
paths:
  /comments:
    post:
      consumes:
        - application/json
      description: create new comment
      produces:
        - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Comment'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpErrors.RestErr'
      summary: Create new comment
      tags:
        - Comments
  /comments/{id}:
    delete:
      consumes:
        - application/json
      description: delete comment
      parameters:
        - description: comment_id
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpErrors.RestErr'
      summary: Delete comment
      tags:
        - Comments
    get:
      consumes:
        - application/json
      description: Get comment by id
      parameters:
        - description: comment_id
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Comment'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpErrors.RestErr'
      summary: Get comment
      tags:
        - Comments
    put:
      consumes:
        - application/json
      description: update new comment
      parameters:
        - description: comment_id
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Comment'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpErrors.RestErr'
      summary: Update comment
      tags:
        - Comments
swagger: "2.0"
